// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('cek-kategori-riwayat', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('cek-kategori-riwayat', async function() {
    // Test name: cek-kategori-riwayat
    // Step # | name | target | value
    // 1 | open | https://stg-web.troben.cloud/ | 
    await driver.get("https://stg-web.troben.cloud/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | linkText=Riwayat | 
    await driver.findElement(By.linkText("Riwayat")).click()
    // 4 | click | xpath=//div[@id='app']/div/div[2]/div/div[2] | 
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div/div[2]")).click()
    // 5 | click | linkText=TrawLpack | 
    await driver.findElement(By.linkText("TrawLpack")).click()
    // 6 | click | xpath=//div[@id='app']/div/div[2]/div/div[2]/div | 
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div/div[2]/div")).click()
    // 7 | click | linkText=TrawLtruck | 
    await driver.findElement(By.linkText("TrawLtruck")).click()
    // 8 | click | xpath=//div[@id='app']/div/div[2]/div/div[2]/div | 
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div/div[2]/div")).click()
    // 9 | click | xpath=//div[@id='app']/div/div[2]/div/div[2]/div | 
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div/div[2]/div")).click()
    // 10 | click | linkText=TrawLcarrier | 
    await driver.findElement(By.linkText("TrawLcarrier")).click()
    // 11 | click | xpath=//button[contains(.,'First')] | 
    await driver.findElement(By.xpath("//button[contains(.,\'First\')]")).click()
    // 12 | click | linkText=Semua | 
    await driver.findElement(By.linkText("Semua")).click()
    // 13 | click | xpath=//button[contains(.,'1')] | 
    await driver.findElement(By.xpath("//button[contains(.,\'1\')]")).click()
    // 14 | click | xpath=//button[contains(.,'2')] | 
    await driver.findElement(By.xpath("//button[contains(.,\'2\')]")).click()
    // 15 | click | xpath=//button[contains(.,'Next')] | 
    await driver.findElement(By.xpath("//button[contains(.,\'Next\')]")).click()
    // 16 | click | xpath=//button[contains(.,'Last')] | 
    await driver.findElement(By.xpath("//button[contains(.,\'Last\')]")).click()
  })
})
