// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login-another account', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login-another account', async function() {
    // Test name: login-another account
    // Step # | name | target | value
    // 1 | open | https://stg-web.troben.cloud/ | 
    await driver.get("https://stg-web.troben.cloud/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | linkText=Masuk | 
    await driver.findElement(By.linkText("Masuk")).click()
    // 4 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 5 | type | name=email | testsqa24@dev.com
    await driver.findElement(By.name("email")).sendKeys("testsqa24@dev.com")
    // 6 | click | xpath=(//input[@name='password'])[2] | 
    await driver.findElement(By.xpath("(//input[@name=\'password\'])[2]")).click()
    // 7 | type | xpath=(//input[@name='password'])[2] | @gen27YASOP
    await driver.findElement(By.xpath("(//input[@name=\'password\'])[2]")).sendKeys("@gen27YASOP")
    // 8 | click | css=.ms-auto > img | 
    await driver.findElement(By.css(".ms-auto > img")).click()
    // 9 | click | css=.ms-auto > img | 
    await driver.findElement(By.css(".ms-auto > img")).click()
    // 10 | click | css=.block | 
    await driver.findElement(By.css(".block")).click()
    // 11 | click | xpath=//button[@type='submit'] | 
    await driver.findElement(By.xpath("//button[@type=\'submit\']")).click()
    // 12 | click | css=.error-message | 
    await driver.findElement(By.css(".error-message")).click()
  })
})
