// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    // Test name: login
    // Step # | name | target | value
    // 1 | open | https://stg-web.troben.cloud/ | 
    await driver.get("https://stg-web.troben.cloud/")
    // 2 | setWindowSize | 1366x728 | 
    await driver.manage().window().setRect({ width: 1366, height: 728 })
    // 3 | click | linkText=Masuk | 
    await driver.findElement(By.linkText("Masuk")).click()
    // 4 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 5 | type | name=email | testsqa24@dev.com
    await driver.findElement(By.name("email")).sendKeys("testsqa24@dev.com")
    // 6 | click | xpath=(//input[@name='password'])[2] | 
    await driver.findElement(By.xpath("(//input[@name=\'password\'])[2]")).click()
    // 7 | type | css=.mt-3 > .pl-3:nth-child(2) | testsqa24
    await driver.findElement(By.css(".mt-3 > .pl-3:nth-child(2)")).sendKeys("testsqa24")
    // 8 | click | xpath=//button[@type='submit'] | 
    await driver.findElement(By.xpath("//button[@type=\'submit\']")).click()
    // 9 | click | linkText=Beranda | 
    await driver.findElement(By.linkText("Beranda")).click()
  })
})
