// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login-google account', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login-google account', async function() {
    // Test name: login-google account
    // Step # | name | target | value
    // 1 | open | https://stg-web.troben.cloud/ | 
    await driver.get("https://stg-web.troben.cloud/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | linkText=Masuk | 
    await driver.findElement(By.linkText("Masuk")).click()
    // 4 | click | xpath=//u[contains(.,'Masuk Dengan Nomor Telepon?')] | 
    await driver.findElement(By.xpath("//u[contains(.,\'Masuk Dengan Nomor Telepon?\')]")).click()
    // 5 | click | xpath=//button[contains(.,'Google')] | 
    await driver.findElement(By.xpath("//button[contains(.,\'Google\')]")).click()
    // 6 | click | css=.md\3A flex | 
    await driver.findElement(By.css(".md\\3A flex")).click()
  })
})
