// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login-number telephone', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login-number telephone', async function() {
    // Test name: login-number telephone
    // Step # | name | target | value
    // 1 | open | https://stg-web.troben.cloud/ | 
    await driver.get("https://stg-web.troben.cloud/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | linkText=Masuk | 
    await driver.findElement(By.linkText("Masuk")).click()
    // 4 | click | xpath=//div[@id='app']/div/div/div[2]/form/div[6]/div/a/u | 
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/form/div[6]/div/a/u")).click()
    // 5 | click | xpath=//div[@id='app']/div/div/div[2]/form/div | 
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/form/div")).click()
    // 6 | click | name=phone | 
    await driver.findElement(By.name("phone")).click()
    // 7 | type | name=phone | 082166837092
    await driver.findElement(By.name("phone")).sendKeys("082166837092")
    // 8 | click | xpath=//div/div/div | 
    await driver.findElement(By.xpath("//div/div/div")).click()
    // 9 | click | xpath=//button[@type='submit'] | 
    await driver.findElement(By.xpath("//button[@type=\'submit\']")).click()
    // 10 | click | css=.error-message | 
    await driver.findElement(By.css(".error-message")).click()
  })
})
