// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('logout', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('logout', async function() {
    // Test name: logout
    // Step # | name | target | value
    // 1 | open | https://stg-web.troben.cloud/ | 
    await driver.get("https://stg-web.troben.cloud/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | linkText=Masuk | 
    await driver.findElement(By.linkText("Masuk")).click()
    // 4 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 5 | type | name=email | testsqa24@dev.com
    await driver.findElement(By.name("email")).sendKeys("testsqa24@dev.com")
    // 6 | click | css=.mt-3 > .pl-3:nth-child(2) | 
    await driver.findElement(By.css(".mt-3 > .pl-3:nth-child(2)")).click()
    // 7 | type | css=.mt-3 > .pl-3:nth-child(2) | testsqa24
    await driver.findElement(By.css(".mt-3 > .pl-3:nth-child(2)")).sendKeys("testsqa24")
    // 8 | click | xpath=//button[@type='submit'] | 
    await driver.findElement(By.xpath("//button[@type=\'submit\']")).click()
    // 9 | click | id=profileDropdownId1 | 
    await driver.findElement(By.id("profileDropdownId1")).click()
    // 10 | click | linkText=Keluar | 
    await driver.findElement(By.linkText("Keluar")).click()
    // 11 | click | xpath=(//button[@type='button'])[3] | 
    await driver.findElement(By.xpath("(//button[@type=\'button\'])[3]")).click()
    // 12 | click | xpath=//div[@id='app']/div/div/header/div/div/div/a/img | 
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div/div/div/a/img")).click()
  })
})
