// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('notifikasi', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('notifikasi', async function() {
    // Test name: notifikasi
    // Step # | name | target | value
    // 1 | open | https://stg-web.troben.cloud/ | 
    await driver.get("https://stg-web.troben.cloud/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | xpath=//li[contains(.,'Notifikasi')] | 
    await driver.findElement(By.xpath("//li[contains(.,\'Notifikasi\')]")).click()
    // 4 | click | linkText=Notifikasi | 
    await driver.findElement(By.linkText("Notifikasi")).click()
    // 5 | click | id=simple-search | 
    await driver.findElement(By.id("simple-search")).click()
    // 6 | type | id=simple-search | Pesanan
    await driver.findElement(By.id("simple-search")).sendKeys("Pesanan")
    // 7 | click | xpath=//u[contains(.,'Tandai semua telah dibaca')] | 
    await driver.findElement(By.xpath("//u[contains(.,\'Tandai semua telah dibaca\')]")).click()
    // 8 | click | xpath=//div[@id='app']/div/div[2]/div/div[2]/div[2]/a/div/div/div[2]/div | 
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div/div[2]/div[2]/a/div/div/div[2]/div")).click()
  })
})
