// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('pengiriman-barang', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('pengiriman-barang', async function() {
    // Test name: pengiriman-barang
    // Step # | name | target | value
    // 1 | open | https://stg-web.troben.cloud/ | 
    await driver.get("https://stg-web.troben.cloud/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | css=.swiper-slide:nth-child(1) .bg-greenPrimary | 
    await driver.findElement(By.css(".swiper-slide:nth-child(1) .bg-greenPrimary")).click()
    // 4 | click | xpath=//input[@type='text'] | 
    await driver.findElement(By.xpath("//input[@type=\'text\']")).click()
    // 5 | type | xpath=//input[@type='text'] | Erikson
    await driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("Erikson")
    // 6 | click | name=price | 
    await driver.findElement(By.name("price")).click()
    // 7 | type | xpath=//input[@name='price'] | 87655644520
    await driver.findElement(By.xpath("//input[@name=\'price\']")).sendKeys("87655644520")
    // 8 | click | css=.mt-4 > .border | 
    await driver.findElement(By.css(".mt-4 > .border")).click()
    // 9 | click | xpath=//div[3]/div/div[2] | 
    await driver.findElement(By.xpath("//div[3]/div/div[2]")).click()
    // 10 | click | css=.mt-4 > .border | 
    await driver.findElement(By.css(".mt-4 > .border")).click()
    // 11 | type | xpath=(//input[@type='text'])[2] | Jl Rasamalaya Raya
    await driver.findElement(By.xpath("(//input[@type=\'text\'])[2]")).sendKeys("Jl Rasamalaya Raya")
    // 12 | click | xpath=(//input[@type='text'])[3] | 
    await driver.findElement(By.xpath("(//input[@type=\'text\'])[3]")).click()
    // 13 | type | css=.p-4:nth-child(3) div:nth-child(1) > .border | Aditya
    await driver.findElement(By.css(".p-4:nth-child(3) div:nth-child(1) > .border")).sendKeys("Aditya")
    // 14 | click | xpath=(//input[@name='price'])[2] | 
    await driver.findElement(By.xpath("(//input[@name=\'price\'])[2]")).click()
    // 15 | type | css=.p-4:nth-child(3) > .grid > div > .relative > .block | 86577677876
    await driver.findElement(By.css(".p-4:nth-child(3) > .grid > div > .relative > .block")).sendKeys("86577677876")
    // 16 | click | xpath=(//input[@type='text'])[4] | 
    await driver.findElement(By.xpath("(//input[@type=\'text\'])[4]")).click()
    // 17 | type | css=.relative:nth-child(3) > .border | Pucangsawit
    await driver.findElement(By.css(".relative:nth-child(3) > .border")).sendKeys("Pucangsawit")
    // 18 | click | css=.p-2 | 
    await driver.findElement(By.css(".p-2")).click()
    // 19 | click | xpath=(//input[@type='text'])[5] | 
    await driver.findElement(By.xpath("(//input[@type=\'text\'])[5]")).click()
    // 20 | type | css=div:nth-child(4) > .border | Jl. Ir. Sutami
    await driver.findElement(By.css("div:nth-child(4) > .border")).sendKeys("Jl. Ir. Sutami")
    // 21 | click | css=.mt-content | 
    await driver.findElement(By.css(".mt-content")).click()
    // 22 | click | xpath=//div[2]/div[2]/div/div[4]/div | 
    await driver.findElement(By.xpath("//div[2]/div[2]/div/div[4]/div")).click()
    // 23 | click | xpath=//div[6]/div/div/div[2]/div | 
    await driver.findElement(By.xpath("//div[6]/div/div/div[2]/div")).click()
    // 24 | click | xpath=//div[6]/div[2]/div/div[2]/div/div | 
    await driver.findElement(By.xpath("//div[6]/div[2]/div/div[2]/div/div")).click()
    // 25 | click | xpath=//label[contains(.,'Regular')] | 
    await driver.findElement(By.xpath("//label[contains(.,\'Regular\')]")).click()
    // 26 | click | xpath=//button[contains(.,'Simpan')] | 
    await driver.findElement(By.xpath("//button[contains(.,\'Simpan\')]")).click()
    // 27 | click | css=.c-toast | 
    await driver.findElement(By.css(".c-toast")).click()
  })
})
